# Generated by Django 6.0.2 on 2026-02-06 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('animal', 'Animal'), ('object', 'Object'), ('place', 'Place'), ('person', 'Person'), ('event', 'Event'), ('abstract', 'Abstract')], max_length=16)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DreamEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('narrative', models.TextField()),
                ('date_dreamed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood_rating', models.SmallIntegerField(blank=True, null=True)),
                ('emotions', models.JSONField(blank=True, default=list)),
                ('people', models.JSONField(blank=True, default=list)),
                ('settings', models.JSONField(blank=True, default=list)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClarifyingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifying_questions', to='journal.dreamentry')),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.CharField(choices=[('psych', 'Psychology'), ('spiritual', 'Spiritual'), ('combined', 'Combined')], max_length=16)),
                ('summary', models.TextField()),
                ('reflection_questions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('prompt_version', models.CharField(blank=True, max_length=32)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='journal.dreamentry')),
            ],
        ),
        migrations.CreateModel(
            name='DreamSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_symbols', to='journal.dreamentry')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_dreams', to='journal.symbol')),
            ],
            options={
                'unique_together': {('dream', 'symbol')},
            },
        ),
        migrations.AddField(
            model_name='dreamentry',
            name='symbols',
            field=models.ManyToManyField(related_name='dreams', through='journal.DreamSymbol', to='journal.symbol'),
        ),
        migrations.AddField(
            model_name='dreamentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dreams', to='journal.tag'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('interpretation_style', models.CharField(choices=[('balanced', 'Balanced'), ('psych', 'Psychology'), ('spiritual', 'Spiritual')], default='balanced', max_length=16)),
                ('privacy_default', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='dreamentry',
            index=models.Index(fields=['user', 'date_dreamed'], name='journal_dre_user_id_00e24e_idx'),
        ),
        migrations.AddIndex(
            model_name='dreamentry',
            index=models.Index(fields=['user', 'created_at'], name='journal_dre_user_id_e830f2_idx'),
        ),
    ]
