# Generated by Django 6.0.2 on 2026-02-07 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='journal.dreamentry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
